[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"

[functions]
  included_files = ["**/*.py"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200
